

 DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
    S_N INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY INT
);

INSERT INTO EMPLOYEE (S_N, NAME, DEPARTMENT, SALARY)
VALUES (1, 'John', 'HR', 50000);
SELECT*FROM EMPLOYEE